### ISSUE TITLE
Do we need a init system?

### ISSUE THREAD

**Issue by gtcno** [nais/baseimages#2]
See  https://github.com/Yelp/dumb-init

**Comment by joakibj** [comment]
Maybe, probably. Otherwise we likely need some different way of starting apps.

In this current baseimage draft and our current app we use `CMD` or `ENTRYPOINT` to start our apps with `sh`.

According to this: https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html the alpine linux shell, /bin/ash does not propagate signals to its children. So the java app does not see the SIGTERM and thus frameworks like spring boot and camel do not gracefully shut down.

We need to verify this behaviour and find a solution, where dumb-init could be one.

@davidsteinsland

**Comment by davidsteinsland** [comment]
We use the exec form to start Java apps, which means they get pid 1. So there shouldn't be any issues regarding signals, but I'll test anyway.

**Comment by giacung** [comment]
Verified that heap dump is possible when running the java process with PID > 1. 
Fails  with PID 1.  Docker > 1.13 has the --init flag which can be set on the the docker hosts
which will run the container with https://github.com/krallin/tini. 

However we still need to include jmap, jstack etc to this baseimage, I think.

**Comment by joakibj** [comment]
Yeah we need this then. Maybe we should set `HeapDumpOnOutOfMemoryError` and `HeapDumpPath` as default flags as well. That way NAIS can automate retrieval of these?

Regarding the jmap, jstack etc utils, they are part of the JDK and not the JRE. So we either need to base the baseimages of the JDK (increasing layer size) or include them through some other mechanism.

**Comment by joakibj** [comment]
@gtcno are you planning to add the `--init` flag when starting docker containers in NAIS? I made a branch adding `dumb-init` to `java-8`, however I guess this is not needed if you guys add the tinit functionality.

Then we only need to add the `openjdk:8-jdk-alpine` to `java-8`. The difference in layer is 22MB which is not huge (although it does compound in the NAV docker registry). However, being able to make heapdumps is useful. @davidsteinsland thoughts?

**Comment by joakibj** [comment]
It wasn't possible to add the `--init` flag globally in NAIS, so we add the `dumb-init` to our baseimages for now.
